### ISSUE TITLE
Editor settings for PlantUML

### ISSUE THREAD

**Issue by asbjornu** [nirix/atom-editor-settings#19]
I'd like to configure `tabLength: 2` for [language-plantuml](https://atom.io/packages/language-plantuml), but don't really understand how to configure it. I've tried to create the file `plantUml.cson` with the following contents:

```yaml
tabLength: 2
    puml:
        tabLength: 2
    pu:
        tabLength: 2
```

But it doesn't seem to work. The tab length used is still `4` when I press tab. Do I need to restart Atom for the changes to be applied? This might be related to #16, because I don't really understand the difference between grammar and file extension. Which of those should the config file be named after and which should be used within the config file? I'm confused. :confused:

**Comment by nirix** [comment]
The `README` doesn't really make it clear on how to create a config file.

Open the command palette (Cmd+Shift+P on OS X) and type in `Editor Settings: Open Grammar Config` and when it pops up press enter.

From there, you can set the tab length. As for file extension configuration:

The options not nested under `extensionConfig` apply to all `PlantUML` files, but if you want to change the tab length for a `PlantUML ` with the file extension of `.pu` for example, then the configuration below will do that:

````
tabLength: 2
extensionConfig:
  pu:
    tabLength: 4
````

**Comment by asbjornu** [comment]
@nirix Thanks. Doing that, opened a file called `plantuml.cson` (notice the lowercase `u`) that looks like this:

```yaml
tabLength: 2
    puml:
        tabLength: 2
    pu:
        tabLength: 2
```

But when pressing tab in a `.puml` file, I still get a 4 space length tab character.

**Comment by nirix** [comment]
Atom is most likely set to use tabs, try this;

````
tabLength: 2
softTabs: true
````

**Comment by asbjornu** [comment]
@nirix That didn't help. Do I need to restart Atom for the changes to be applied?

**Comment by asbjornu** [comment]
@nirix I fixed it by reducing the config to:

```yaml
tabLength: 2
```

Seems like the `puml:` and/or `pu:` sections broke it. Any idea why?

**Comment by nirix** [comment]
The `puml:` and `pu:` sections must not have been nested under `extensionConfig:` like so:

````
tabLength: 2
extensionConfig:
  puml:
    tabLength: 2
  pu:
    tabLength: 2
````
